// Supabase Database Types
// This file will be auto-generated by: npm run supabase:generate
// For now, using placeholder types

/* eslint-disable @typescript-eslint/no-explicit-any */

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          telegram_id: string
          username: string
          first_name: string
          last_name: string
          photo_url: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          telegram_id: string
          username: string
          first_name: string
          last_name: string
          photo_url?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          telegram_id?: string
          username?: string
          first_name?: string
          last_name?: string
          photo_url?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      transactions: {
        Row: {
          id: string
          user_id: string
          type: string
          amount: number
          currency: string
          status: string
          reference_id: string | null
          created_at: string
          description?: string | null
          metadata?: Record<string, any> | null
        }
        Insert: {
          id: string
          user_id: string
          type: string
          amount: number
          currency: string
          status: string
          reference_id?: string | null
          created_at?: string
          description?: string | null
          metadata?: Record<string, any> | null
        }
        Update: {
          id?: string
          user_id?: string
          type?: string
          amount?: number
          currency?: string
          status?: string
          reference_id?: string | null
          created_at?: string
          description?: string | null
          metadata?: Record<string, any> | null
        }
      }
      profiles: {
        Row: {
          id: string
          telegram_id?: string | null
          username?: string | null
          first_name?: string | null
          last_name?: string | null
          avatar_url?: string | null
          country?: string | null
          language?: string | null
          level?: number | null
          rank?: string | null
          energy?: number | null
          available_fc?: number | null
          withdrawal_progress?: number | null
          is_premium?: boolean | null
          status?: string | null
          fraud_score?: number | null
          device_info?: Record<string, any> | null
          created_at?: string
          updated_at?: string
        }
        Insert: {
          id: string
          telegram_id?: string | null
          username?: string | null
          first_name?: string | null
          last_name?: string | null
          avatar_url?: string | null
          country?: string | null
          language?: string | null
          level?: number | null
          rank?: string | null
          energy?: number | null
          available_fc?: number | null
          withdrawal_progress?: number | null
          is_premium?: boolean | null
          status?: string | null
          fraud_score?: number | null
          device_info?: Record<string, any> | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          telegram_id?: string | null
          username?: string | null
          first_name?: string | null
          last_name?: string | null
          avatar_url?: string | null
          country?: string | null
          language?: string | null
          level?: number | null
          rank?: string | null
          energy?: number | null
          available_fc?: number | null
          withdrawal_progress?: number | null
          is_premium?: boolean | null
          status?: string | null
          fraud_score?: number | null
          device_info?: Record<string, any> | null
          created_at?: string
          updated_at?: string
        }
      }
      wallets: {
        Row: {
          id: string
          user_id: string
          fc_balance: number
          pending_earnings: number
          withdrawable_balance: number
          available_fc?: number | null
          pending_fc?: number | null
          energy?: number | null
          max_energy?: number | null
          withdrawal_progress?: number | null
          estimated_unlock_date?: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          user_id: string
          fc_balance: number
          pending_earnings: number
          withdrawable_balance: number
          available_fc?: number | null
          pending_fc?: number | null
          energy?: number | null
          max_energy?: number | null
          withdrawal_progress?: number | null
          estimated_unlock_date?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          fc_balance?: number
          pending_earnings?: number
          withdrawable_balance?: number
          available_fc?: number | null
          pending_fc?: number | null
          energy?: number | null
          max_energy?: number | null
          withdrawal_progress?: number | null
          estimated_unlock_date?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      support_tickets: {
        Row: {
          id: string
          user_id: string
          subject: string
          status: string
          priority: string
          category: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          user_id: string
          subject: string
          status: string
          priority: string
          category: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          subject?: string
          status?: string
          priority?: string
          category?: string
          created_at?: string
          updated_at?: string
        }
      }
      support_messages: {
        Row: {
          id: string
          ticket_id: string
          user_id: string
          message: string
          is_from_support: boolean
          attachments?: string[] | null
          created_at: string
        }
        Insert: {
          id: string
          ticket_id: string
          user_id: string
          message: string
          is_from_support: boolean
          attachments?: string[] | null
          created_at?: string
        }
        Update: {
          id?: string
          ticket_id?: string
          user_id?: string
          message?: string
          is_from_support?: boolean
          attachments?: string[] | null
          created_at?: string
        }
      }
      tasks: {
        Row: {
          id: string
          user_id?: string | null
          title?: string | null
          description?: string | null
          provider_name?: string | null
          reward_amount?: number | null
          status?: string | null
          type?: string | null
          created_at?: string
          completed_at?: string | null
          metadata?: Record<string, any> | null
        }
        Insert: {
          id: string
          user_id?: string | null
          title?: string | null
          description?: string | null
          provider_name?: string | null
          reward_amount?: number | null
          status?: string | null
          type?: string | null
          created_at?: string
          completed_at?: string | null
          metadata?: Record<string, any> | null
        }
        Update: {
          id?: string
          user_id?: string | null
          title?: string | null
          description?: string | null
          provider_name?: string | null
          reward_amount?: number | null
          status?: string | null
          type?: string | null
          created_at?: string
          completed_at?: string | null
          metadata?: Record<string, any> | null
        }
      }
      missions: {
        Row: {
          id: string
          user_id: string
          title?: string | null
          description?: string | null
          type?: string | null
          status?: string | null
          reward?: number | null
          progress?: number | null
          target?: number | null
          created_at?: string
          completed_at?: string | null
        }
        Insert: {
          id: string
          user_id: string
          title?: string | null
          description?: string | null
          type?: string | null
          status?: string | null
          reward?: number | null
          progress?: number | null
          target?: number | null
          created_at?: string
          completed_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          title?: string | null
          description?: string | null
          type?: string | null
          status?: string | null
          reward?: number | null
          progress?: number | null
          target?: number | null
          created_at?: string
          completed_at?: string | null
        }
      }
      referrals: {
        Row: {
          id: string
          referrer_id: string
          referred_id: string
          status?: string | null
          reward_amount?: number | null
          created_at?: string
          converted_at?: string | null
        }
        Insert: {
          id: string
          referrer_id: string
          referred_id: string
          status?: string | null
          reward_amount?: number | null
          created_at?: string
          converted_at?: string | null
        }
        Update: {
          id?: string
          referrer_id?: string
          referred_id?: string
          status?: string | null
          reward_amount?: number | null
          created_at?: string
          converted_at?: string | null
        }
      }
      leaderboard: {
        Row: {
          id: string
          user_id: string
          username?: string | null
          first_name?: string | null
          score?: number | null
          rank_change?: number | null
          period?: string | null
          created_at?: string
        }
        Insert: {
          id: string
          user_id: string
          username?: string | null
          first_name?: string | null
          score?: number | null
          rank_change?: number | null
          period?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          username?: string | null
          first_name?: string | null
          score?: number | null
          rank_change?: number | null
          period?: string | null
          created_at?: string
        }
      }
      withdrawals: {
        Row: {
          id: string
          user_id: string
          amount: number
          method: string
          status: string
          created_at: string
          processed_at?: string | null
          settlement_cycle?: string | null
          profiles?: Record<string, any> | null
        }
        Insert: {
          id: string
          user_id: string
          amount: number
          method: string
          status: string
          created_at?: string
          processed_at?: string | null
          settlement_cycle?: string | null
          profiles?: Record<string, any> | null
        }
        Update: {
          id?: string
          user_id?: string
          amount?: number
          method?: string
          status?: string
          created_at?: string
          processed_at?: string | null
          settlement_cycle?: string | null
          profiles?: Record<string, any> | null
        }
      }
    }
    Functions: {
      increment_wallet_balance: {
        Args: {
          p_user_id: string
          p_amount: number
        }
        Returns: unknown
      }
      get_user_stats: {
        Args: {
          p_user_id: string
        }
        Returns: unknown
      }
      [key: string]: {
        Args: Record<string, any>
        Returns: unknown
      }
    }
  }
}
