export { supabase, type SupabaseClient } from './client'
export { adminClient, type AdminSupabaseClient } from './admin'
export { serverClient, type ServerSupabaseClient } from './server'
export { validateEnv, type EnvConfig } from './env-validation'
export { db } from './database'
export { handleSupabaseError, type SupabaseError } from './error-handler'
export { logger, type LoggerOptions } from './logger'
export { realtime } from './realtime'
export { storage } from './storage'
export { edgeFunctions } from './edge-functions'
export { auth } from './auth'
export { session } from './session'
export { rls } from './rls'
export { queryBuilder } from './query-builder'
export { pagination, type PaginationOptions, type PaginatedResult } from './pagination'
export { formatResponse, type ApiResponse, type PaginatedResponse } from './response'
export type { Database } from '@/types/supabase'